-- ============================================================================
-- vaporlog — Supabase schema
-- ============================================================================
-- Paste this ENTIRE file into the Supabase SQL Editor (SQL → New query) and
-- run it once. It is IDEMPOTENT: re-running it on the same project is safe
-- (tables/indexes use IF NOT EXISTS, policies and triggers are dropped
-- before being recreated, functions use CREATE OR REPLACE).
--
-- What this sets up:
--   1. public.profiles  — one row per auth user: handle (unique,
--      case-insensitive), birthdate. Created automatically by a trigger on
--      auth.users — clients never insert into it directly.
--   2. public.sessions  — vaporization session logs. Column set mirrors the
--      app's SessionLog shape (src/lib/types.ts) in snake_case, plus
--      user_id for ownership and a denormalized `author` handle.
--   3. Row-level security on both tables.
--
-- NOTE for the app layer: SessionLog (src/lib/types.ts) has `amountG`,
-- `moods`, `activities` and `author`, and has NO `effects` / `sessionAt`
-- fields — so this schema carries amount_g / moods / activities / author
-- and intentionally omits effects and session_at. created_at doubles as
-- SessionLog.createdAt.
-- ============================================================================


-- ============================================================================
-- 1. profiles
-- ============================================================================
-- One row per Supabase auth user. `id` is both the PK and a FK to
-- auth.users — deleting the auth user cascades the profile away.
-- There is deliberately NO client INSERT policy: rows are created only by
-- the handle_new_user trigger (section 4), which reads the handle and
-- birthdate from the sign-up metadata.

create table if not exists public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  -- Pseudonym. Always stored lowercase (the trigger lowercases it); the app
  -- treats handles as case-insensitive everywhere.
  handle     text not null,
  -- 21+ age-gate date (YYYY-MM-DD). Nullable so a malformed/absent metadata
  -- value can never block account creation.
  birthdate  date,
  created_at timestamptz not null default now()
);

-- Case-insensitive uniqueness of handles. This index is the REAL guard
-- against taken handles (the app also pre-checks for a friendly error, but
-- only this index is race-proof). A collision here aborts the auth.users
-- insert via the trigger, which Supabase surfaces as a database error that
-- the app maps to "That handle is taken."
create unique index if not exists profiles_handle_lower_key
  on public.profiles (lower(handle));


-- ============================================================================
-- 2. sessions
-- ============================================================================
-- Column set mirrors SessionLog (src/lib/types.ts) in snake_case:
--
--   SessionLog       sessions column        notes
--   -------------    ---------------------  ------------------------------
--   id               id                     uuid, generated by the DB
--   —                user_id                owner (not part of SessionLog)
--   strainSlug       strain_slug
--   deviceSlug       device_slug            SessionLog: non-null string
--   temperatureC     temperature_c          nullable (optional in the app)
--   durationMin      duration_min           nullable (optional in the app)
--   amountG          amount_g               nullable (optional in the app)
--   rating           rating                 1–10 per app contract
--   aromas           aromas
--   flavors          flavors
--   moods            moods
--   activities       activities
--   notes            notes
--   isPublic         is_public
--   author           author                 denormalized handle (trigger)
--   createdAt        created_at

create table if not exists public.sessions (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles (id) on delete cascade,
  strain_slug   text not null,
  device_slug   text not null default '',
  temperature_c numeric,
  duration_min  numeric,
  amount_g      numeric,
  rating        numeric not null,
  aromas        text[] not null default '{}',
  flavors       text[] not null default '{}',
  moods         text[] not null default '{}',
  activities    text[] not null default '{}',
  notes         text not null default '',
  is_public     boolean not null default false,
  -- Denormalized copy of profiles.handle so community feeds render without
  -- a join. Maintained by the set_session_author trigger (section 5) —
  -- clients may leave it empty on insert.
  author        text not null default '',
  created_at    timestamptz not null default now()
);

-- Community feed: public sessions, newest first.
create index if not exists sessions_public_created_idx
  on public.sessions (is_public, created_at desc);

-- "My sessions" lookups.
create index if not exists sessions_user_id_idx
  on public.sessions (user_id);


-- ============================================================================
-- 3. Row-level security
-- ============================================================================
-- Supabase's default privileges grant table privileges to the anon and
-- authenticated roles on public-schema tables; RLS is what decides which
-- ROWS each role can see or change. These policies therefore apply to
-- signed-in users AND anonymous visitors alike.

alter table public.profiles enable row level security;
alter table public.sessions enable row level security;

-- profiles: readable by everyone (handles are public pseudonyms — the
-- community feed and the sign-up taken-check both rely on this).
drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all"
  on public.profiles for select
  using (true);

-- profiles: users may update only their own row (e.g. a future
-- handle-change flow). NO insert/delete policy — the trigger owns inserts,
-- and profile deletion happens only via auth user deletion (cascade).
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- sessions: a row is visible when it is public OR belongs to the reader.
-- Anonymous visitors (auth.uid() is null) see exactly the public rows.
drop policy if exists "sessions_select_public_or_own" on public.sessions;
create policy "sessions_select_public_or_own"
  on public.sessions for select
  using (is_public or auth.uid() = user_id);

-- sessions: writes are owner-only.
drop policy if exists "sessions_insert_own" on public.sessions;
create policy "sessions_insert_own"
  on public.sessions for insert
  with check (auth.uid() = user_id);

drop policy if exists "sessions_update_own" on public.sessions;
create policy "sessions_update_own"
  on public.sessions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "sessions_delete_own" on public.sessions;
create policy "sessions_delete_own"
  on public.sessions for delete
  using (auth.uid() = user_id);


-- ============================================================================
-- 4. New-user trigger: auth.users → profiles
-- ============================================================================
-- Runs once per sign-up, inside the same transaction as the auth.users
-- insert (so a failure here aborts the whole sign-up). SECURITY DEFINER so
-- it can insert into profiles despite there being no client INSERT policy.
-- Reads `handle` and `birthdate` from the sign-up metadata the app passes
-- via supabase.auth.signUp({ options: { data: { handle, birthdate } } }).

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_handle    text;
  v_birthdate date;
begin
  -- Handle from metadata, lowercased (uniqueness is case-insensitive).
  -- Fallback: the local part of the synthetic email — the app maps handles
  -- to `<handle>@vaporlog.app`, so that local part IS the handle.
  v_handle := lower(nullif(new.raw_user_meta_data ->> 'handle', ''));
  if v_handle is null then
    v_handle := lower(split_part(new.email, '@', 1));
  end if;

  -- Birthdate from metadata. A malformed value must never block sign-up:
  -- swallow cast errors and store NULL (the column is nullable).
  begin
    v_birthdate := nullif(new.raw_user_meta_data ->> 'birthdate', '')::date;
  exception when others then
    v_birthdate := null;
  end;

  insert into public.profiles (id, handle, birthdate)
  values (new.id, v_handle, v_birthdate);

  return new;
end;
$$;

-- Drop first so re-running this file never errors on an existing trigger.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ============================================================================
-- 5. sessions.author maintenance
-- ============================================================================
-- Keeps the denormalized author handle correct without trusting the client:
--   a) set_session_author stamps every inserted row (and re-stamps if a
--      row's owner ever changes) from profiles.handle;
--   b) sync_author_on_handle_change cascades a profile handle change onto
--      that user's existing session rows.
-- Both are SECURITY DEFINER so they work regardless of the caller's RLS
-- context; they only ever touch rows tied to the triggering user.

create or replace function public.set_session_author()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_handle text;
begin
  select handle into v_handle
    from public.profiles
   where id = new.user_id;
  new.author := coalesce(v_handle, '');
  return new;
end;
$$;

drop trigger if exists sessions_set_author on public.sessions;
create trigger sessions_set_author
  before insert or update of user_id on public.sessions
  for each row execute function public.set_session_author();

create or replace function public.sync_author_on_handle_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.handle is distinct from old.handle then
    update public.sessions
       set author = new.handle
     where user_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_sync_author on public.profiles;
create trigger profiles_sync_author
  after update of handle on public.profiles
  for each row execute function public.sync_author_on_handle_change();

-- ============================================================================
-- Done. Quick sanity checks (run separately if desired):
--   select * from public.profiles;
--   select * from public.sessions;
--   select tablename, policyname from pg_policies where schemaname = 'public';
-- ============================================================================
